import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LeftSideBar from "@/components/LeftSideBar";
import StaticHeadBar from "@/components/StaticHeadBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Metaetiqueta para deshabilitar el zoom pero mantener el scroll */}
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main>
          <div className="container">
            <StaticHeadBar />
            <LeftSideBar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
